### ISSUE TITLE
Issue sending to your servers ASR via HTTP

### ISSUE THREAD

**Issue by noelruault** [NuanceDev/ndev-python-http-cli#7]
I work with python 2.7, I had all libraries and drivers installed previous to this step.
Well, I followed your tutorial, step by step, and found any solvable errors but I can not handle this next:
When I try do the connection via HTTP to your servers, this is what happens:

WITHOUT SSL:
![issue01](https://cloud.githubusercontent.com/assets/4104120/8909129/0eccc3de-3480-11e5-92e9-ec4cebbb680c.jpg)
WITH SSL:
![issue03](https://cloud.githubusercontent.com/assets/4104120/8909135/1562e5fc-3480-11e5-98fa-fa63398d8b9c.jpg)

On the one hand, I analyzed your code and do not find nothing strange. I also tried ignore SIG_PIPE and don't throw exceptions on it (link on bibliography), but this do not fix nothing, I only get the same interruption without the error [Errno 32] Broken pipe.
On the other, it is obvious (without SSL) anything is wrong. I do not know how fix it, but with SSL, at least (it seems) I can send the file successfully, but the answer of the server is: ' '

At this point, I have spent many hours trying to fix it so I need help.

BIBLIOGRAPHY.
http://dragonmobile.nuancemobiledeveloper.com//phpbb/viewforum.php?f=21
http://nuancedev.github.io/samples/http/python/#capturing-audio
http://newbebweb.blogspot.com.es/2012/02/python-head-ioerror-errno-32-broken.html

**Comment by Noelou93** [comment]
SOLVED, credentials.json error.
Now with this ones, the connection is successful
{
"appId":"NMDPTRIAL_sales_aisoy_com20150721135426",
"appKey": "8b96e02300274d3eeda01b9997eef0b42d6b507599ae916b8a9165f8caf945568f2579904cc7ce3967e9d3fed8c3b3052e037ac7b20b323c9c9734679179bd20",
"asrUrl": "https://dictation.nuancemobility.net",
"asrEndpoint": "/NMDPAsrCmdServlet/dictation",
"ttsUrl": "https://tts.nuancemobility.net:443",
"ttsEndpoint": "/NMDPTTSCmdServlet/tts"
}
